/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://gj7lkydmp5fctahvalxoxetilu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-nrvdet2fhbej7eja2nmj2ggyhu",
    "aws_cognito_identity_pool_id": "us-east-1:1c50c525-51e2-486d-9cf5-ba044a681956",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_bDE6hcVtg",
    "aws_user_pools_web_client_id": "4g4a0m1mj29j2fekoqvqfntu0j",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "oltv1-storage174911-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
